export const apiUrl: string = "https://dashboard.wisefollowup.com/api/v1/";
export const baseUrl: string = "https://appadvertisements.almasader.net";
export const apiRoutes = {
  login: "/auth/login",
  register: "auth/register",
  sendOtp: "auth/send_otp",
  forgetPasswordOtp: "forget_password/verfication",
  cart: "cart",
  addresses: "addresses",
  news_letter: "newsletter",
  categories_list: "categories/list",
  checkOTP: "/auth/check_otp",
  resetPassword: "auth/reset_password",
  changePassword: "auth/changePassword",
  about: "about",
  cities: "cities",
  leaflets: "leaflets",
  wishlist: "wishlist/toggle",
  faqs: "faqs",
  simpleCategories: "/categories/simple",
  favorites: "wishlist/list",
  brands: "brands",
  static_pages: "static-pages/list",
  static_page: "static-pages",
  updateProfile: "auth/updateProfile",
  setting: "settings",
  blogs: "blogs",
  flash_sale: "products/flash-sale",
  reviews: "reviews",
  myReviews: "reviews/my-reviews",
  sliders: "sliders",
  banner: "hero-section",
  search: "products/search",
  allCopouns: "coupons/list",
  applyCoupon: "coupons/check",
  orders: "orders",
  features: "/features/list",
  gallery: "galleries",
  ads: "banners/list",
  testimonials: "testimonials",
  alertUser: "/stock-alerts",
  cartRemoveItems: "cart/items/delete-many",
  removeCoupon: "cart/remove-coupon",
  notifications: "/notifications",
  contactStore: "contact-us/store",
  contactSettings: "settings/contact",
  counties: "/counties",
  countries: "/countries", orgTypes: "/organization-types", organizations: "/organizations", departments: "departments", years: "/leaflets/years-stats", privacy: "static-pages/privacy-policy",
  cookies: "static-pages/cookies-policy",
  terms: "static-pages/terms-of-use",
  disclaimer: "static-pages/medical-disclaimer",
};
